version: '3'
services:
  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    volumes:
      - mongodb-data:/data/db

  nodejs:
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongodb

volumes:
  mongodb-data:

